[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["crates/day_1", "crates/day_10", "crates/day_11", "crates/day_2", "crates/day_3", "crates/day_4", "crates/day_5", "crates/day_6", "crates/day_7", "crates/day_8", "crates/day_9"]

